### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tom-NL** [Nico-Pergande/np_statusbot#1]
getting the bot not working, continuous node event errors. What can I do about it

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}
npm WARN bot.squid-dev.eu@1.0.0 No description
npm WARN bot.squid-dev.eu@1.0.0 No repository field.

audited 29 packages in 4.139s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/container/node_modules/discord.js/src/client/BaseClient.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/container/node_modules/discord.js/src/client/BaseClient.js',
    '/home/container/node_modules/discord.js/src/index.js',
    '/home/container/index.js'
  ]
}
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}
npm WARN bot.squid-dev.eu@1.0.0 No description
npm WARN bot.squid-dev.eu@1.0.0 No repository field.

added 29 packages from 89 contributors and audited 29 packages in 16.603s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/container/node_modules/discord.js/src/client/BaseClient.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/container/node_modules/discord.js/src/client/BaseClient.js',
    '/home/container/node_modules/discord.js/src/index.js',
    '/home/container/index.js'
  ]
}
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}
npm WARN bot.squid-dev.eu@1.0.0 No description
npm WARN bot.squid-dev.eu@1.0.0 No repository field.

audited 29 packages in 4.401s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/container/node_modules/discord.js/src/client/BaseClient.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/container/node_modules/discord.js/src/client/BaseClient.js',
    '/home/container/node_modules/discord.js/src/index.js',
    '/home/container/index.js'
  ]
}
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by Kayne64** [comment]
do `npm i` and it should fix it

**Comment by Tom-NL** [comment]
done but then other errors come back

**Comment by Tom-NL** [comment]
Error: Cannot find module 'C:\Users\Administrator\Downloads\np_statusbot-main\index.jef'
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)[39m
[90m    at node:internal/main/run_main_module:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
PS C:\Users\Administrator\Downloads\np_statusbot-main> node index.js
C:\Users\Administrator\Downloads\np_statusbot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:245
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\Administrator\Downloads\np_statusbot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:245:15)
    at async Client.login (C:\Users\Administrator\Downloads\np_statusbot-main\node_modules\discord.js\src\client\Client.js:254:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
PS C:\Users\Administrator\Downloads\np_statusbot-main>

**Comment by Nico-Pergande** [comment]
it has to be index.js NOT index,jef

**Comment by Nico-Pergande** [comment]
you have to activate this to intents at the discord-bot-site too
![image](https://user-images.githubusercontent.com/72522450/183397437-496e43d8-fd6e-4cfb-802a-4b87aea0ccb1.png)

**Comment by Tom-NL** [comment]
should I have it on or off?

**Comment by Nico-Pergande** [comment]
both has to on

**Comment by Tom-NL** [comment]
I did that and if it doesn't update or idk how can I notice because when I turn off the server everything stays green

and see this message as well:
Error: AxiosError: Request failed with status code 404

**Comment by Tom-NL** [comment]
what is a solution for that?
